api:
  error:
    #認証
    E0001: #ユーザーが見つからない
      code: E0001
      message: user not found...
    E0002: #パスワードが間違っている
      code: E0002
      message: password is wrong...
    E0003: #認証が通っていない
      code: E0003
      message: unauthenticated...
    #users_controller
    E0004:
      code: E0004 #ユーザー作成に失敗
      message: illegal create user params...
    E0005:
      code: E0005  #ロール作成に失敗
      message: illegal create role params...
    E0006:
      code: E0006
      message: user records are maximum... #ユーザー件数が既に3件存在する
    E0007:
      code: E0007 #ユーザーが既に削除済み
      message: already deleted user...
    E9999: # 想定外のエラー
      code: E9999
      message: unexpected error...
  status:
    Java:
      default:
        hp: 40
        mp: 20
        attack: 15
        defence: 20
        next_level_point: 10
      update:
        hp: 10
        mp: 10
        attack: 10
        defence: 10
        next_level_point_base_value: 10
    Ruby:
      default:
        hp: 30
        mp: 30
        attack: 20
        defence: 10
        next_level_point: 10
      update:
        hp: 10
        mp: 10
        attack: 10
        defence: 10
        next_level_point_base_value: 10
    Rust:
      default:
        hp: 50
        mp: 30
        attack: 10
        defence: 20
        next_level_point: 10
      update:
        hp: 10
        mp: 10
        attack: 10
        defence: 10
        next_level_point_base_value: 10
  enemy:
    - stage_level: 1
      name: Duke